"""Header generation for SimpleGFXfont from glyph and bitmap data."""

import os
from typing import List, Tuple
from .bitmap_utils import (
    bytes_per_row,
    format_c_byte_list,
    format_c_code_list,
    gen_bitmap_bytes,
)


def generate_header(
    font_name: str,
    out_path: str,
    chars: List[int],
    width: int,
    height: int,
    xadvance: int,
    yadvance: int,
    xoffset: int,
    yoffset: int,
    fill: int,
    grayscale: bool = True,
):
    bitmap_all = []
    bitmap_lsb_all = []
    bitmap_msb_all = []
    glyphs = []
    offset = 0
    for ch in chars:
        bm = gen_bitmap_bytes(width, height, fill)
        bitmap_all.extend(bm)
        # If grayscale disabled, we still need pixel_values for size but
        # the per-pixel values will all be 0 (white) or max if fill is set.
        pixel_values = [3 if fill else 0] * (width * height)
        # If grayscale is enabled, compute LSB/MSB planes for 2-bit grayscale
        if grayscale:
            lsb_values = [val & 1 for val in pixel_values]
            msb_values = [(val >> 1) & 1 for val in pixel_values]
            lsb_chunk = []
            for y in range(height):
                for x in range(0, width, 8):
                    byte_val = 0
                    for i in range(8):
                        if x + i < width:
                            idx = y * width + x + i
                            bit_val = lsb_values[idx]
                            byte_val |= bit_val << (7 - i)
                    lsb_chunk.append(byte_val)
            bitmap_lsb_all.extend(lsb_chunk)
            msb_chunk = []
            for y in range(height):
                for x in range(0, width, 8):
                    byte_val = 0
                    for i in range(8):
                        if x + i < width:
                            idx = y * width + x + i
                            bit_val = msb_values[idx]
                            byte_val |= bit_val << (7 - i)
                    msb_chunk.append(byte_val)
            bitmap_msb_all.extend(msb_chunk)
        glyph = {
            "bitmapOffset": offset,
            "width": width,
            "height": height,
            "xAdvance": xadvance,
            "xOffset": xoffset,
            "yOffset": yoffset,
            "pixel_values": pixel_values,
        }
        glyphs.append(glyph)
        offset += len(bm)

    bmp_lines = []
    bmp_lsb_lines = []
    bmp_msb_lines = []
    for idx, ch in enumerate(chars):
        g = glyphs[idx]
        per_glyph_bytes = bytes_per_row(g["width"]) * g["height"]
        start = g["bitmapOffset"]
        end = start + per_glyph_bytes
        chunk = bitmap_all[start:end]
        chunk_lsb = bitmap_lsb_all[start:end]
        chunk_msb = bitmap_msb_all[start:end]
        display = chr(ch)
        comment = f"// 0x{ch:X} '{display}'"
        chunk_c = format_c_byte_list(chunk)
        chunk_lsb_c = format_c_byte_list(chunk_lsb)
        chunk_msb_c = format_c_byte_list(chunk_msb)
        bmp_lines.append(f"    {comment}\n{chunk_c}")
        bmp_lsb_lines.append(f"    {comment}\n{chunk_lsb_c}")
        bmp_msb_lines.append(f"    {comment}\n{chunk_msb_c}")
    bmp_c = ",\n".join(bmp_lines)
    bmp_lsb_c = ",\n".join(bmp_lsb_lines)
    bmp_msb_c = ",\n".join(bmp_msb_lines)
    glyph_lines = []
    for idx, g in enumerate(glyphs):
        ch = chars[idx]
        glyph_lines.append(
            f"    {{{g['bitmapOffset']}, 0x{ch:X}, {g['width']}, {g['height']}, {g['xAdvance']}, {g['xOffset']}, {g['yOffset']}}}"
        )
    glyphs_c = ",\n".join(glyph_lines)

    count = len(chars)

    #    When grayscale is disabled we omit the _lsb/_msb arrays and set the
    #    corresponding struct pointers to nullptr in the SimpleGFXfont initializer.
    #    When grayscale is disabled we omit the _lsb/_msb arrays and set the
    #    corresponding struct pointers to nullptr in the SimpleGFXfont initializer.
    header = f"""#pragma once
#include "rendering/SimpleFont.h"

// Generated by generate_simplefont.py
// Font: {font_name}

const uint8_t {font_name}Bitmaps[] PROGMEM = {{
{bmp_c}
}};

"""
    if grayscale:
        header += f"\nconst uint8_t {font_name}Bitmaps_lsb[] PROGMEM = {{\n{bmp_lsb_c}\n}};\n\n"
        header += f"\nconst uint8_t {font_name}Bitmaps_msb[] PROGMEM = {{\n{bmp_msb_c}\n}};\n\n"

    # Glyphs array
    header += (
        f"\nconst SimpleGFXglyph {font_name}Glyphs[] PROGMEM = {{\n{glyphs_c}\n}};\n\n"
    )

    # Final font struct initializer: pick pointers or nullptr based on grayscale
    if grayscale:
        header += f"\nconst SimpleGFXfont {font_name} PROGMEM = {{{font_name}Bitmaps, {font_name}Bitmaps_lsb, {font_name}Bitmaps_msb, {font_name}Glyphs,\n    {count}, {yadvance}}};\n"
    else:
        header += (
            f"\nconst SimpleGFXfont {font_name} PROGMEM = {{{font_name}Bitmaps, nullptr, nullptr, {font_name}Glyphs,\n"
            f"    {count}, {yadvance}}};\n"
        )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print(f"Wrote {out_path}")
    return glyphs, bitmap_all, bitmap_lsb_all, bitmap_msb_all


def write_header_from_data(
    font_name: str,
    out_path: str,
    chars: List[int],
    glyphs: List[dict],
    bitmap_all: List[int],
    bitmap_lsb_all: List[int],
    bitmap_msb_all: List[int],
    yadvance: int,
    grayscale: bool = True,
):
    bmp_lines = []
    bmp_lsb_lines = []
    bmp_msb_lines = []
    for idx, ch in enumerate(chars):
        g = glyphs[idx]
        per_glyph_bytes = bytes_per_row(g["width"]) * g["height"]
        start = g["bitmapOffset"]
        end = start + per_glyph_bytes
        chunk = bitmap_all[start:end]
        chunk_lsb = bitmap_lsb_all[start:end]
        chunk_msb = bitmap_msb_all[start:end]
        display = chr(ch)
        comment = f"// 0x{ch:X} '{display}'"
        chunk_c = format_c_byte_list(chunk)
        chunk_lsb_c = format_c_byte_list(chunk_lsb)
        chunk_msb_c = format_c_byte_list(chunk_msb)
        bmp_lines.append(f"    {comment}\n{chunk_c}")
        bmp_lsb_lines.append(f"    {comment}\n{chunk_lsb_c}")
        bmp_msb_lines.append(f"    {comment}\n{chunk_msb_c}")
    bmp_c = ",\n".join(bmp_lines)
    bmp_lsb_c = ",\n".join(bmp_lsb_lines)
    bmp_msb_c = ",\n".join(bmp_msb_lines)

    glyph_lines = []
    for idx, g in enumerate(glyphs):
        ch = chars[idx]
        glyph_lines.append(
            f"    {{{g['bitmapOffset']}, 0x{ch:X}, {g['width']}, {g['height']}, {g['xAdvance']}, {g['xOffset']}, {g['yOffset']}}}"
        )
    glyphs_c = ",\n".join(glyph_lines)

    count = len(chars)

    # Build header string
    header = f"""#pragma once
#include "rendering/SimpleFont.h"

// Generated by generate_simplefont.py
// Font: {font_name}

const uint8_t {font_name}Bitmaps[] PROGMEM = {{
{bmp_c}
}};

"""
    if grayscale:
        header += f"\nconst uint8_t {font_name}Bitmaps_lsb[] PROGMEM = {{\n{bmp_lsb_c}\n}};\n\n"
        header += f"\nconst uint8_t {font_name}Bitmaps_msb[] PROGMEM = {{\n{bmp_msb_c}\n}};\n\n"

    # Glyphs array
    header += (
        f"\nconst SimpleGFXglyph {font_name}Glyphs[] PROGMEM = {{\n{glyphs_c}\n}};\n\n"
    )

    if grayscale:
        header += f"\nconst SimpleGFXfont {font_name} PROGMEM = {{{font_name}Bitmaps, {font_name}Bitmaps_lsb, {font_name}Bitmaps_msb, {font_name}Glyphs,\n    {count}, {yadvance}}};\n"
    else:
        header += (
            f"\nconst SimpleGFXfont {font_name} PROGMEM = {{{font_name}Bitmaps, nullptr, nullptr, {font_name}Glyphs,\n"
            f"    {count}, {yadvance}}};\n"
        )

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print(f"Wrote {out_path}")
